Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "server.cluster.org"
  config.vm.network :private_network, ip: "192.168.90.2"
  config.vm.network :forwarded_port, host: 9080, guest: 80
  config.vm.provider :virtualbox do |vm|
    vm.memory = 4096
    vm.cpus = 4
  end

  # config.vm.provision :shell, path: "torque-install-third-party.sh"
  # config.vm.provision :shell, path: "torque-compile.sh"
  # config.vm.provision :shell, path: "apache-install-configure.sh"
  config.vm.provision :shell, path: "torque-server-install-configure.sh"
  config.vm.provision :shell, path: "torque-mom-install-configure.sh"
end