$setup = <<SCRIPT
echo 192.168.0.2 master.example >> /etc/hosts
echo 192.168.0.3 slave1.example >> /etc/hosts
echo 192.168.0.4 slave2.example >> /etc/hosts

echo deb http://master.example/deb amd64/ >> /etc/apt/sources.list
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "slave1.example"
  config.vm.network :private_network, ip: "192.168.0.3"
  config.vm.provider :virtualbox do |vm|
    vm.memory = 2048
    vm.cpus = 1
  end
 config.vm.provision "shell", inline: $setup
end