Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "node1.cluster.org"
  config.vm.network :private_network, ip: "192.168.90.3"
  config.vm.provider :virtualbox do |vm|
    vm.memory = 2048
    vm.cpus = 2
  end

  config.vm.provision :shell, path: "torque-mom-install-configure.sh", args: "server.cluster.org 192.168.90.2 http://192.168.90.2/deb/amd64"
end